// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi6YCs6yVDGVdD_5cJG8BlM5pKXPratMU',
    appId: '1:939943950889:web:16f167519c9724b9befa38',
    messagingSenderId: '939943950889',
    projectId: 'opname-merchandise',
    authDomain: 'opname-merchandise.firebaseapp.com',
    storageBucket: 'opname-merchandise.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9YRNDLnlLkjGFveo-a7VFQtFmIMkJFJY',
    appId: '1:939943950889:android:75f3ce47bd00aeb6befa38',
    messagingSenderId: '939943950889',
    projectId: 'opname-merchandise',
    storageBucket: 'opname-merchandise.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmYbli1hlqW4MNCL-nxRewaf2b84cI-Hk',
    appId: '1:939943950889:ios:17e7ee9890f7e2e2befa38',
    messagingSenderId: '939943950889',
    projectId: 'opname-merchandise',
    storageBucket: 'opname-merchandise.firebasestorage.app',
    iosBundleId: 'com.example.opnameMerchandise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmYbli1hlqW4MNCL-nxRewaf2b84cI-Hk',
    appId: '1:939943950889:ios:17e7ee9890f7e2e2befa38',
    messagingSenderId: '939943950889',
    projectId: 'opname-merchandise',
    storageBucket: 'opname-merchandise.firebasestorage.app',
    iosBundleId: 'com.example.opnameMerchandise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi6YCs6yVDGVdD_5cJG8BlM5pKXPratMU',
    appId: '1:939943950889:web:85bb4be6a8cf4c65befa38',
    messagingSenderId: '939943950889',
    projectId: 'opname-merchandise',
    authDomain: 'opname-merchandise.firebaseapp.com',
    storageBucket: 'opname-merchandise.firebasestorage.app',
  );
}
